- id: asciidoc-link-check
  name: Asciidoc Link Check
  description: Extracts links from asciidoc texts and checks they're all alive (i.e. return status 200 OK).
  entry: asciidoc-link-check
  language: node
  types: [asciidoc]
  stages: [commit, push, manual]
