name: asciidoc-link-check
version: git
summary: Checks if all hyperlinks in an asciidoc file are alive(or dead).
description: |
  Check links for a local file:
    $ asciidoc-link-check README.adoc --progress
  Check links for an online file:
    $ asciidoc-link-check https://github.com/gaurav-nelson/asciidoc-link-check/blob/master/README.adoc
  Check links from standard input:
    $ cat <filename>.adoc | asciidoc-link-check -p
  Check links in all asciidoc files in the current directory:
    $ find . -name \*.adoc -exec asciidoc-link-check -p {} \;
  Ignore specific links:
    $ asciidoc-link-check README.adoc -c <configfile.json>

base: core18
confinement: strict

parts:
  asciidoc-link-check:
    plugin: nodejs
    source: .

apps:
  asciidoc-link-check:
    command: asciidoc-link-check